### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by jnothman** [martingerlach/hSBM_Topicmodel#1]
Hi Martin, Thanks for speaking at Sydney U the other day. I'm wondering what licence you apply to the code here. Could you please add a `LICENSE.txt`, to help others understand what derivative works are licensed? Thanks.

**Comment by martingerlach** [comment]
Hi Joel,
I added a license --  GNU General Public License v3.0.
I hope that clarifies your question. Let me know if you have other questions regarding the code.
Best,
Martin
