### ISSUE TITLE
Cannot plot fitted model

### ISSUE THREAD

**Issue by sergejkaiser** [martingerlach/hSBM_Topicmodel#7]
After fitting the model, I tried to use the plotting. However, it failed. I guess some error with graph_tool
AttributeError                            Traceback (most recent call last)
<ipython-input-38-24bd70afb218> in <module>
----> 1 model.plot()

/work/scripts/sbmtm.py in plot(self, filename, nedges)
    182         '''
    183         self.state.draw(layout='bipartite', output=filename,
--> 184                         subsample_edges=nedges, hshortcuts=1, hide=0)
    185 
    186 

/usr/lib/python3/dist-packages/graph_tool/inference/nested_blockmodel.py in draw(self, **kwargs)
    932         draws the hierarchical state."""
    933         import graph_tool.draw
--> 934         return graph_tool.draw.draw_hierarchy(self, **kwargs)
    935 
    936 

AttributeError: module 'graph_tool.draw' has no attribute 'draw_hierarchy'

**Comment by jnothman** [comment]
You probably have an old version of graph_tool installed. Try following the
instructions at
https://topsbm.readthedocs.io/en/latest/install.html#installing-dependencies

**Comment by sergejkaiser** [comment]
Thanks. Installing gtk and the python bindings of it, solved the issue.
